In [25]:
import xarray as xr
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
data

<xarray.Dataset>
Dimensions:    (latitude: 241, level: 4, longitude: 361, time: 6)
Coordinates:
  * longitude  (longitude) float32 -100.0 -99.75 -99.5 -99.25 -99.0 -98.75 ...
  * latitude   (latitude) float32 10.0 9.75 9.5 9.25 9.0 8.75 8.5 8.25 8.0 ...
  * level      (level) int32 250 500 850 1000
  * time       (time) datetime64[ns] 2017-02-02 2017-02-02T06:00:00 ...
Data variables:
    z          (time, level, latitude, longitude) float32 ...
    r          (time, level, latitude, longitude) float32 ...
    crwc       (time, level, latitude, longitude) float32 ...
    t          (time, level, latitude, longitude) float32 ...
    u          (time, level, latitude, longitude) float32 ...
    v          (time, level, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2019-04-15 13:52:49 GMT by grib_to_netcdf-2.10.0: /opt/ecmw...

In [109]:
data = xr.open_dataset('../ERA5/ps_levels_02-02.nc')

rh = data['r'][:][:][]
rh

<xarray.DataArray 'r' (time: 6, level: 4, latitude: 241, longitude: 361)>
[2088024 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -100.0 -99.75 -99.5 -99.25 -99.0 -98.75 ...
  * latitude   (latitude) float32 10.0 9.75 9.5 9.25 9.0 8.75 8.5 8.25 8.0 ...
  * level      (level) int32 250 500 850 1000
  * time       (time) datetime64[ns] 2017-02-02 2017-02-02T06:00:00 ...
Attributes:
    units:          %
    long_name:      Relative humidity
    standard_name:  relative_humidity

In [106]:
xr.DataArray.to_dataframe(rh)

                                        time          r
level latitude longitude
250    10.0    -100.00   2017-02-02 15:00:00  11.632343
               -99.75    2017-02-02 15:00:00  11.924686
               -99.50    2017-02-02 15:00:00  12.439377
               -99.25    2017-02-02 15:00:00  12.807896
               -99.00    2017-02-02 15:00:00  12.822304
               -98.75    2017-02-02 15:00:00  12.939655
               -98.50    2017-02-02 15:00:00  12.620548
               -98.25    2017-02-02 15:00:00  12.361145
               -98.00    2017-02-02 15:00:00  12.169678
               -97.75    2017-02-02 15:00:00  12.046154
               -97.50    2017-02-02 15:00:00  12.042034
               -97.25    2017-02-02 15:00:00  12.128502
               -97.00    2017-02-02 15:00:00  12.287029
               -96.75    2017-02-02 15:00:00  12.385849
               -96.50    2017-02-02 15:00:00  12.620548
               -96.25    2017-02-02 15:00:00  12.803776
               -96.00    2017-02-02 15:00:00  13.073475
               -95.75    2017-02-02 15:00:00  13.357582
               -95.50    2017-02-02 15:00:00  13.736393
               -95.25    2017-02-02 15:00:00  14.158440
               -95.00    2017-02-02 15:00:00  14.489899
               -94.75    2017-02-02 15:00:00  14.823418
               -94.50    2017-02-02 15:00:00  15.014885
               -94.25    2017-02-02 15:00:00  15.068413
               -94.00    2017-02-02 15:00:00  15.064293
               -93.75    2017-02-02 15:00:00  15.072529
               -93.50    2017-02-02 15:00:00  14.986061
               -93.25    2017-02-02 15:00:00  14.994297
               -93.00    2017-02-02 15:00:00  14.876945
               -92.75    2017-02-02 15:00:00  14.776070
...                                      ...        ...
1000  -50.0    -17.25    2017-02-02 15:00:00  85.720909
               -17.00    2017-02-02 15:00:00  85.622086
               -16.75    2017-02-02 15:00:00  85.574738
               -16.50    2017-02-02 15:00:00  85.564438
               -16.25    2017-02-02 15:00:00  85.455322
               -16.00    2017-02-02 15:00:00  85.270035
               -15.75    2017-02-02 15:00:00  85.130043
               -15.50    2017-02-02 15:00:00  84.973579
               -15.25    2017-02-02 15:00:00  84.697701
               -15.00    2017-02-02 15:00:00  84.360069
               -14.75    2017-02-02 15:00:00  84.028610
               -14.50    2017-02-02 15:00:00  83.641556
               -14.25    2017-02-02 15:00:00  83.227753
               -14.00    2017-02-02 15:00:00  82.914818
               -13.75    2017-02-02 15:00:00  82.665710
               -13.50    2017-02-02 15:00:00  82.352776
               -13.25    2017-02-02 15:00:00  82.064552
               -13.00    2017-02-02 15:00:00  81.943085
               -12.75    2017-02-02 15:00:00  81.903969
               -12.50    2017-02-02 15:00:00  81.844261
               -12.25    2017-02-02 15:00:00  81.877205
               -12.00    2017-02-02 15:00:00  82.017197
               -11.75    2017-02-02 15:00:00  82.122192
               -11.50    2017-02-02 15:00:00  82.177780
               -11.25    2017-02-02 15:00:00  82.330132
               -11.00    2017-02-02 15:00:00  82.540123
               -10.75    2017-02-02 15:00:00  82.622475
               -10.50    2017-02-02 15:00:00  82.606003
               -10.25    2017-02-02 15:00:00  82.630707
               -10.00    2017-02-02 15:00:00  82.630707

[348004 rows x 2 columns]